[tool.poetry]
name = "tsururu"
version = "0.1.0"
description = "Python tool for time series forecasting"
authors = ["Alina Kostromina <AMaKostromina@sberbank.ru>", "Dmitry Simakov <Simakov.D.E@sberbank.ru>"]
license = "Apache License 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
scikit-learn = "^1.3.2"
numpy = "^1.26.3"
pandas = "^2.1.4"
holidays = "^0.40"

# models
catboost = {version = "^1.2.2", optional = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
models = ["catboost"]
