[tool.poetry]
name = "tsururu"
description = "Python tool for time series forecasting"
version = "0.1.0"

authors = ["Alina Kostromina" <"AMaKostromina@sberbank.ru">,
           "Dmitry Simakov" <"Simakov.D.E@sberbank.ru">]

readme = "README.md"

repository = "https://github.com/sberbank-ai-lab/tsururu"

classifiers = [
    "Programming Language :: Python :: 3.9",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Natural Language :: Russian",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[tool.poetry.dependencies]

python = ">=3.9"

scikit-learn = "*"
numpy = "*"
pandas = "*"
holidays = "*"

# models
catboost = {version = "*", optional = true}

[tool.poetry.extras]
models = [
    "catboost",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 99

[tool.isort]
profile = "black"